openapi: 3.0.3
info:
  title: Products API
  description: |-
    An api for my Products API
  contact:
    email: aaron.o.scherling@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: auth
    description: Login and Signup
  - name: products
    description: Access to products
paths:
  /auth/login:
    summary: Operation to login
    get:
      tags:
        - auth
      parameters:
        - name: userName
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        400:
          description: Incorrect input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadParamsError'
  /auth/signup:
    summary: Operation to login
    put:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - userName
                - password
              properties:
                firstName:
                  type: string
                  example: 'John'
                lastName:
                  type: string
                  example: 'Doe'
                userName:
                  type: string
                  example: 'John_doe'
                password:
                  type: string
                  example: 'abc123'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        400:
          description: Incorrect input
        default:
          description: Incorrect input
  /products/{id}:
    get:
      tags:
        - products
      summary: retrieve product list by id
      parameters:
        - name: id
          in: path
          description: ID of the product to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
components:
  schemas:
    BadParamsError:
      type: object
      properties:
        message:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        userName:
          type: string
          example: theUser
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: James
        password:
          type: string
          example: '12345'
  # Not setup below
  #   ApiResponse:
  #     type: object
  #     properties:
  #       code:
  #         type: integer
  #         format: int32
  #       type:
  #         type: string
  #       message:
  #         type: string
  #     xml:
  #       name: '##default'
  # requestBodies:
  #   Pet:
  #     description: Pet object that needs to be added to the store
  #     content:
  #       application/json:
  #         schema:
  #           $ref: '#/components/schemas/Pet'
  #       application/xml:
  #         schema:
  #           $ref: '#/components/schemas/Pet'
  #   UserArray:
  #     description: List of user object
  #     content:
  #       application/json:
  #         schema:
  #           type: array
  #           items:
  #             $ref: '#/components/schemas/User'
  # securitySchemes:
  #   petstore_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: https://petstore3.swagger.io/oauth/authorize
  #         scopes:
  #           write:pets: modify pets in your account
  #           read:pets: read your pets
  #   api_key:
  #     type: apiKey
  #     name: api_key
  #     in: header
